server:
  port: 8000
spring:
  application:
    name : gms-config
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181

    config:
      server:
        git:
          uri: https://gitee.com/chenmwork/gms-config
          username: 502298798@qq.com
          password: Chenmin2015