server:
  port: 7098
spring:
  application:
    name : gms-order-service
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: true
  identity: MYSQL

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000

