server:
  port: 7088

spring:
  application:
    name : gms-pro-server
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/item?characterEncoding=utf-8&useSSL=true
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml

mapper:
  identity: MYSQL
  not-empty: true

logging:
  level:
    com.chenm.gms.gmspro.mapper: debug
